---
name: iplike-build
run-name: Build PostgreSQL iplike extension
on:
  push:

## Build and create the project on every push to the project
jobs:
  build:
    strategy:
      matrix:
        pg_version: [ 10, 11, 12, 13, 14, 15, 16, 17 ]
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/iplike-builder:0.2.0.b1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Update generated configuration files
        run: |
          autoreconf -fvi
      - name: Configure and build from source
        run: |
          ./configure --with-pgsql=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config
          make
      - name: Create Debian packages
        run: |
          dpkg-buildpackage
      - name: Collect build artifacts
        run: |
          mkdir -p debian/artifacts
          mv ../iplike-pgsql* debian/artifacts
      - name: Persist build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iplike-pgsql-${{ matrix.pg_version }}
          path: debian/artifacts/*
      - name: Publish Debian packages to Cloudsmith
        # Only publish release artifacts on pushing a Git tag with a version number starting with v*
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          for deb in $(ls debian/artifacts/iplike-pgsql${{ matrix.pg_version }}_*.deb); do
            cloudsmith push deb bluebird/common/any-distro/any-version ${deb};
          done;
