---
name: iplike-build
run-name: Build PostgreSQL iplike extension
on:
  push:

## Build and create the project on every push to the project
jobs:
  build:
    strategy:
      matrix:
        pg_version: [ 13, 14, 15, 16, 17, 18 ]
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/iplike-builder:0.2.2.b9
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Update generated configuration files
        run: |
          autoreconf -fvi
      - name: Configure and build from source
        run: |
          ./configure --with-pgsql=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config
          make
      - name: Create Debian packages
        run: |
          dpkg-buildpackage
      - name: Collect Debian build artifacts
        run: |
          mkdir -p debian/artifacts
          mv ../iplike-pgsql* debian/artifacts
      - name: Persist Debian build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iplike-pgsql-${{ matrix.pg_version }}-deb
          path: debian/artifacts/*
      - name: Create RPM packages
        run: |
          make rpm
      - name: Collect RPM build artifacts
        run: |
          mkdir -p rpm/artifacts
          mv "${HOME}/rpmbuild" rpm/artifacts
      - name: Persist RPM build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iplike-pgsql-${{ matrix.pg_version }}-rpm
          path: rpm/artifacts/*
      - name: Publish Debian packages to Cloudsmith
        # Only publish release artifacts on pushing a Git tag with a version number starting with v*
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          for deb in $(find ./debian/artifacts/iplike-pgsql${{ matrix.pg_version }}_*.deb); do
            cloudsmith push deb bluebird/common/any-distro/any-version ${deb};
          done;
      - name: Publish RPM packages to Cloudsmith
        # Only publish release artifacts on pushing a Git tag with a version number starting with v*
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          for rpm in $(find ./rpm/artifacts -iname "iplike-pgsql${{ matrix.pg_version }}*.rpm"); do
            cloudsmith push rpm bluebird/common/any-distro/any-version ${rpm};
          done;
